---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: hello_hapi
  - name: depedency-cache

run:
  path: hello_hapi/ci/scripts/run_tests.sh
  
